# Agent configuration
agent:
  interval: 3600  # seconds between forecast updates

# Collector configuration
collector:
  type: prometheus
  url: http://localhost:8082
  lookback_days: 7
  step: "1h"  # Consistent step size for all queries
  disable_ssl: true
  timeout: 300
  max_retries: 3
  chunk_days: 0.25  # 6 hours for better granular processing, and so 1 for 24 hours

# Model configuration
models:
  type: toto
  forecast_horizon: 3 # number of days ahead in future
  quantiles: [0.1, 0.5, 0.9]
  toto:
    checkpoint: Datadog/Toto-Open-Base-1.0
    device: cpu              # or cuda
    context_length: 4096
    num_samples: 256
    compile: True

# Optimizer configuration
optimizer:
  idle_cpu_threshold: 0.3
  idle_mem_threshold: 0.3
  min_node_savings: 1

# Metrics configuration
metrics:
  forecast_api_port: 8081
  forecast_api_host: "0.0.0.0"

# Validation configuration
validation:
  enabled: True
  interval_cycles: 2  # Run validation every 5 forecast cycles
  train_ratio: 0.7    # Use 70% for training, 30% for testing
  log_level: INFO

# Node normalization configuration
node_normalization:
  enabled: True
  kube_node_info_query: "kube_node_info"  # Query to get node mappings
  fallback_to_original: True  # Return original name if no mapping found
  log_mapping_stats: True  # Log mapping statistics for debugging
