[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "forecasting-agent"
version = "0.1.0"
description = "A forecasting agent for cost optimization"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "prometheus-api-client",
    "prophet",
    "plotly",
    "prometheus-client"
]


[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
]
[tool.pdm]
distribution = false
