[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "forecasting-agent"
version = "0.1.0"
description = "A forecasting agent for cost optimization"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "prometheus-api-client",
    "prometheus-client",
    "darts==0.34.0",
    "scipy<1.16",
    "pyyaml",
    "matplotlib",
    "plotly",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pdm]
distribution = false

[tool.poetry.dependencies]
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
