[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "forecasting-agent"
version = "0.1.0"
description = "A forecasting agent for cost optimization"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "prometheus-api-client",
    "prometheus-client",
    "darts==0.34.0",
    "scipy<1.16",
    "pyyaml",
    "matplotlib",
    "plotly",
    "torch",  # required for Toto model
    "einops", # Toto dataset utilities
    "jaxtyping", # type annotations used in Toto utilities
    "transformers",
    "aioboto3==12.4.0",
    "beartype==0.18.5",
    "boto3==1.34.69",
    "datasets==2.17.1",
    "dill==0.3.8",
    "einops==0.7.0",
    "gluonts[torch]==0.15.1",
    "jaxtyping==0.2.29",
    "mypy==1.11.1",
    "rotary-embedding-torch==0.8.6",
    "types-tabulate==0.9.0.20241207",
    "tqdm==4.66.3",
    "types-PyYAML==6.0.12.20240917",
    "black==24.10.0",
    "isort==5.13.2",
    "tabulate==0.9.0", 
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pdm]
distribution = false

[tool.poetry.dependencies]
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
