apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting-agent
  namespace: kof
  labels:
    app: forecasting-agent
spec:
  selector:
    matchLabels:
      app: forecasting-agent
  template:
    metadata:
      labels:
        app: forecasting-agent
    spec:
      containers:
      - name: forecasting-agent
        image: ramessesii/forecasting-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: forecasting-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: forecasting-agent
  namespace: kof
  labels:
    app: forecasting-agent
spec:
  ports:
  - port: 8081
    targetPort: metrics
    name: metrics
  selector:
    app: forecasting-agent
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forecasting-agent
  namespace: kof
  labels:
    release: kof-mothership
spec:
  selector:
    matchLabels:
      app: forecasting-agent
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forecasting-agent-config
  namespace: kof
data:
  config.yaml: |
    # Collector configuration
    collector:
      type: prometheus
      url: http://kof-mothership-promxy:8082
      lookback_days: 2
      step: "1h"
      headers: {}
      disable_ssl: true

    # Model configuration
    models:
      type: nbeats
      forecast_horizon: 30
      nbeats:
        freq: "h"
        input_chunk_length: 24
        output_chunk_length: 24
        n_epochs: 50
        activation: ReLU
        random_state: 42
        generic_architecture: true
        likelihood: "QuantileRegression"

    # Optimizer configuration
    optimizer:
      idle_threshold: 0.5
      min_savings: 100.0
      min_confidence: 0.8
      lookback_days: 7

    # Metrics configuration
    metrics:
      port: 8081
      host: 0.0.0.0
      path: /metrics

    # Agent configuration
    agent:
      interval: 300
      log_level: INFO 