apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: forecasting-agent
  namespace: kof
spec:
  username: forecasting-agent
  password: forecasting-agent-secret  # This will be automatically hashed
  targetRefs:
    - crd:
        kind: VMCluster/vmselect
        name: cluster
        namespace: kof
  max_concurrent_requests: 100
  load_balancing_policy: least_loaded
  metric_labels:
    app: forecasting-agent 